CREATE DATABASE IF NOT EXISTS fhir_soap_record CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fhir_soap_record;

CREATE TABLE IF NOT EXISTS Patient (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  gender VARCHAR(50) NOT NULL,
  birth_date DATE NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Contact (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patient_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  relationship VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_contact_patient FOREIGN KEY (patient_id) REFERENCES Patient(id)
);

CREATE TABLE IF NOT EXISTS ContactPoint (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patient_id INT NULL,
  `system` VARCHAR(100) NOT NULL,
  value VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_contact_point (`system`, value, patient_id),
  CONSTRAINT fk_contact_point_patient FOREIGN KEY (patient_id) REFERENCES Patient(id)
);

CREATE TABLE IF NOT EXISTS Identifier (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patient_id INT NULL,
  `system` VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_identifier (`system`, value),
  CONSTRAINT fk_identifier_patient FOREIGN KEY (patient_id) REFERENCES Patient(id)
);

CREATE TABLE IF NOT EXISTS Appointment (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patient_id INT NOT NULL,
  start DATETIME NOT NULL,
  end DATETIME NOT NULL,
  status VARCHAR(100) NOT NULL,
  appointment_type VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES Patient(id)
);

CREATE TABLE IF NOT EXISTS GeneralSetting (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  property VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AuthUser (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  crm VARCHAR(100) NOT NULL,
  crm_uf VARCHAR(10) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_auth_user_crm (crm, crm_uf)
);

CREATE TABLE IF NOT EXISTS AuthToken (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_used_at DATETIME NULL,
  revoked_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_auth_token_hash (token_hash),
  CONSTRAINT fk_auth_token_user FOREIGN KEY (user_id) REFERENCES AuthUser(id)
);

CREATE TABLE IF NOT EXISTS SoapNote (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patient_id INT NOT NULL,
  author_user_id INT NOT NULL,
  encountered_at DATETIME NOT NULL,
  subjective TEXT NOT NULL,
  objective TEXT NOT NULL,
  assessment TEXT NOT NULL,
  plan TEXT NOT NULL,
  source_system VARCHAR(255) NULL,
  source_record_id VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_soap_source (source_system, source_record_id),
  CONSTRAINT fk_soap_note_patient FOREIGN KEY (patient_id) REFERENCES Patient(id),
  CONSTRAINT fk_soap_note_author FOREIGN KEY (author_user_id) REFERENCES AuthUser(id)
);

CREATE TABLE IF NOT EXISTS AuditLog (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  category VARCHAR(100) NOT NULL,
  action VARCHAR(255) NOT NULL,
  entity_type VARCHAR(100) NULL,
  entity_id VARCHAR(100) NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_log_user FOREIGN KEY (user_id) REFERENCES AuthUser(id)
);
